runtime: php55
api_version: 1

handlers:

- url: /
  script: index.html

- url: /email.php
  script: email.php

- url: /data.php
  script: data.php


- url: /contacto.html
  script: contacto.html

- url: /index.html
  script: index.html

- url: /seguimiento.html
  script: seguimiento.html

- url: /carrito.html
  script: carrito.html

- url: /juegosPs1.html
  script: juegosPs1.html

- url: /juegosBusqueda.html
  script: juegosBusqueda.html

- url: /img/
  static_dir: img

- url: /componentes/
  static_dir: componentes

- url: /libreriasJs/
  static_dir: libreriasJs

- url: /paginas/
  static_dir: paginas

- url: /jsones/
  static_dir: jsones

- url: /funcionesPhp/
  static_dir: funcionesPhp

- url: /(.+\.php)$
  script: \1
  
- url: /(.*\.(gif|png|jpg|php|css|js))$
  static_files: /\1
  upload: /.*\.(gif|png|jpg|php|css|js)$

